// PROMPT-AUTH-1 — regenerate the frontend mirror of the text-engine runtime blocks.
//
// The text X-Ray (VERIFY SETTER PROMPT, text mode) shows the runtime-appended
// blocks so the operator sees the TRUE final prompt. The instruction constants
// live in trigger/_shared (the code of record); the frontend can't import across
// the Vite root, so this script emits a byte-identical mirror that
// trigger/_shared/textEngineBlocksMirror.test.ts then enforces.
//
// Run after changing MULTI_MESSAGE_INSTRUCTION / TOOL_USAGE_INSTRUCTION /
// buildAvailabilityBlock / buildTimeAnchorBlock:
//   node --experimental-strip-types scripts/generate_text_engine_mirror.mjs

import { writeFileSync } from "fs";
import { MULTI_MESSAGE_INSTRUCTION, TOOL_USAGE_INSTRUCTION } from "../trigger/_shared/setterTools.ts";
import { buildAvailabilityBlock } from "../trigger/_shared/prefetchSlots.ts";
import { buildTimeAnchorBlock } from "../trigger/_shared/timeAnchor.ts";

const SAMPLE_PREFETCH = {
  status: "ok",
  timezone: "Australia/Brisbane",
  windowDays: 14,
  slots: {
    "2026-07-06": ["08:00", "08:30", "09:00", "11:00", "14:00", "16:00"],
    "2026-07-07": ["09:00", "10:30", "13:00", "15:30"],
    "2026-07-08": ["08:30", "11:00", "14:30"],
  },
  invocation: { name: "get-available-slots", args: {} },
};

// Fixed instant so the sample is stable: Friday 2026-07-03 14:20 in Brisbane.
const SAMPLE_NOW_MS = Date.parse("2026-07-03T04:20:00Z");

const sampleLeadContext = `## Lead Context\nName: Jane Example\nEmail: jane@example.com\nPhone: +61400000000`;
const sampleAvailability = buildAvailabilityBlock(SAMPLE_PREFETCH);
const sampleTimeAnchor = buildTimeAnchorBlock("Australia/Brisbane", SAMPLE_NOW_MS);

const s = (v) => JSON.stringify(v);

const out = `// AUTO-GENERATED by scripts/generate_text_engine_mirror.mjs (PROMPT-AUTH-1).
// Do NOT edit by hand. MULTI_MESSAGE_INSTRUCTION and TOOL_USAGE_INSTRUCTION are
// byte-identical mirrors of trigger/_shared/setterTools.ts, enforced by
// trigger/_shared/textEngineBlocksMirror.test.ts. The SAMPLE_* blocks are
// representative outputs of the runtime builders (regenerated by the script,
// not byte-enforced) used by the text X-Ray to show the TRUE final prompt.

export const MULTI_MESSAGE_INSTRUCTION = ${s(MULTI_MESSAGE_INSTRUCTION)};

export const TOOL_USAGE_INSTRUCTION = ${s(TOOL_USAGE_INSTRUCTION)};

export const SAMPLE_LEAD_CONTEXT = ${s(sampleLeadContext)};

export const SAMPLE_AVAILABILITY_BLOCK = ${s(sampleAvailability)};

export const SAMPLE_TIME_ANCHOR_BLOCK = ${s(sampleTimeAnchor)};
`;

writeFileSync(new URL("../frontend/src/data/textEngineRuntimeBlocks.ts", import.meta.url), out);
console.log("wrote frontend/src/data/textEngineRuntimeBlocks.ts");
